repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/iterative/dvc
    rev: main
    hooks:
      - id: dvc-post-checkout
        additional_dependencies:
          - dvc[all]
        language_version: python3
        stages:
          - post-checkout
        always_run: true
