name: Test and Lint

on:
  push:
    branches:
      - base-software

jobs:
  container:
    runs-on: ubuntu-20.04
    env:
      DB_HOSTNAME: ${{ secrets.DB_HOSTNAME }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.7'

        - name: Install dependencies
          run: pip install -r requirements.txt

        - name: Run tests
          run: pytest test

        - name: Run linting
          run: |
            pylint src test

        - name: Load data
          run: python src/components/data_loader.py
